name: Files Added Hook

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_DEFAULT_REGION: us-east-1
  AWS_DEFAULT_OUTPUT: json
  GCP_KEY: ${{ secrets.GCP_KEY }}

jobs:
  build:

    runs-on: ubuntu-latest
    environment: bugalert-invoke-lambda
    steps:
      - uses: actions/checkout@v2
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          ls -ltah "${GITHUB_WORKSPACE}"
          sudo apt-get update && sudo apt-get install awscli python3-pip -y
          #pip3 install requests==2.26.0 pydub==0.25.1 google-cloud-texttospeech==2.9.0
          pip3 install -Ur "${GITHUB_WORKSPACE}/notice_communication/requirements.txt"
          #aws sts get-caller-identity --region us-east-1
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for added_file in ${added_files[@]}; do
            if [[ $added_file == content/notices/* ]]; then
              echo "File added: ${added_file}."
              python3 "${GITHUB_WORKSPACE}/notice_communication/__main__.py" "${added_file}"
            fi
          done
