name: Files Added Hook

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - id: files
        uses: jitterbit/get-changed-files@v1
        with:
          format: 'json'
      - run: |
          env
          sudo apt-get update && sudo apt-get install awscli -y
          aws sts get-caller-identity --region us-east-1
          readarray -t added_files <<<"$(jq -r '.[]' <<<'${{ steps.files.outputs.added }}')"
          for added_file in ${added_files[@]}; do
            if [[ $added_file == content/notices/* ]]; then
              echo "File added: ${added_file}."
            fi
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DOES_THIS_WORK: Yes
          AWS_DEFAULT_REGION: us-east-1
          AWS_DEFAULT_OUTPUT: json
