name: Pelican CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: bugalert-invoke-lambda

    steps:
    - uses: actions/checkout@v2
    - run: |
        cd "${GITHUB_WORKSPACE}"
         git clone git@github.com:BugAlertDotOrg/bugalert-pelican.git
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: bugalert.org
