name: Pelican CI

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    environment: bugalert-invoke-lambda

    steps:
    - name: Checkout bugalert
      uses: actions/checkout@v2
    - name: Checkout bugalert-pelican
      uses: actions/checkout@v2
      with:
        repository: BugAlertDotOrg/bugalert-pelican
        path: './bugalert-pelican/'
    - run: |
        cp ./bugalert-pelican/requirements.txt .
        sudo apt-get update && DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC sudo apt-get install tzdata python3-pip -y
        export TZ=Etc/UTC
    - uses: nelsonjchen/gh-pages-pelican-action@0.1.10
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        GH_PAGES_CNAME: bugalert.org
        PELICAN_CONFIG_FILE: bugalert-pelican/pelicanconf.py
